# Generated by Django 4.1.7 on 2023-05-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Rezervacija', 'verbose_name_plural': 'Rezervacijos'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Žinutė', 'verbose_name_plural': 'Žinutės'},
        ),
        migrations.AlterModelOptions(
            name='posting',
            options={'verbose_name': 'Skelbimas', 'verbose_name_plural': 'Skelbimai'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Įvertinimas', 'verbose_name_plural': 'Įvertinimai'},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='post',
            new_name='posting',
        ),
        migrations.AlterField(
            model_name='posting',
            name='description',
            field=models.TextField(help_text='Pastabos, jei yra'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Kaina eurais', max_digits=8),
        ),
    ]
