# Generated by Django 4.1.7 on 2023-05-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_booking_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Viršelis'),
        ),
    ]
