# Generated by Django 4.1.7 on 2023-05-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posting_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='cover',
        ),
    ]
