# Generated by Django 4.1.7 on 2023-05-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_review_posting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
