# Generated by Django 4.1.7 on 2023-05-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_review_reviewee_alter_review_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posting',
            options={'ordering': ['start_time'], 'verbose_name': 'Skelbimas', 'verbose_name_plural': 'Skelbimai'},
        ),
        migrations.AlterField(
            model_name='posting',
            name='available_seats',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
