# Generated by Django 4.1.7 on 2023-05-04 12:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_posting_options_alter_posting_available_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Kaina eurais', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
